- hosts: all
  #   become: true

  tasks:
    - name: stop current running container
      command: docker stop my_cicd_project
      ignore_errors: yes

    - name: remove stopped cotainer
      command: docker rm my_cicd_project
      ignore_errors: yes

    - name: remove current docker image
      command: docker rmi yoon11/cicd-project-ansible
      ignore_errors: yes

    - name: pull the newest image from Docker hub
      command: docker pull yoon11/cicd-project-ansible

    - name: create a container using cicd-project-ansible image
      command: docker run --privileged -d --name my_cicd_project -p 8082:8080 yoon11/cicd-project-ansible