apiVersion: v1
kind: Service
metadata:
  name: cicd-service
  labels:
    app: cicd-devops-project
spec:
  selector:
    app: cicd-devops-project
    color: green
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
